CLASS zrsek_bp_employee DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zrsek_r_employee.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zrsek_bp_employee IMPLEMENTATION.
ENDCLASS.

